services:
  postgres:
    image: postgres:13
    container_name: postgres_globant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
# networks:
#   default:
#     external:
#       name: airflow_pg_net¬
